version: '3.3'

volumes:
  postgres_data:
  static-data:

services:
  db:
    image: postgres:12.4-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  web:
    image: vilbert55/yamdb_yc:latest
    restart: always
    expose:
      - 8000
    volumes:
      - static-data:/static/
    depends_on:
      - db
    command: python /code/manage.py collectstatic

  nginx:
    restart: always
    image: nginx:latest
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    volumes:
      - /docker.conf:/etc/nginx/conf.d
      - static-data:/static/
    depends_on:
      - web       
        