version: '3.3'

volumes:
  postgres_data:
  static-data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env

  web:
    image: vilbert55/yamdb_yc:latest
    restart: always
    expose:
      - 8000
    volumes:
      - static-data:/static/
    depends_on:
      - db
    command: bash -c "python manage.py collectstatic --noinput && python manage.py migrate --noinput && gunicorn api_yamdb.wsgi:application --bind 0.0.0.0:8000"

  nginx:
    restart: always
    image: nginx:1.18.0
    ports:
      - "80:80"
    environment:
      - NGINX_HOST=127.0.0.1
      - NGINX_PORT=80
    volumes:
      - ./docker.conf:/etc/nginx/conf.d/docker.conf
      - static-data:/static/
    depends_on:
      - web       
        